# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 10c66e2434f3640b57ada27a13b96d487b95af1dd34d58df8028b453f79c02ed8a68614378840c88ba27c39d46f4c4f36cec2f409b834f350bb595b5d8eed813

test:
  secret_key_base: 051347f9036daf78f4d85c3d89763db39b2e72d51a825ce31799337ce53fc7cdbd4e909d22e202a07ea4146b9359dbd6328cd5c48cbfee41fff4d5052157520e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
